# Getting Things Done in Python

This notebook contains tips and tricks of working with vectors and matrices:
* How to generate arrays of numbers
* How to generate, matrices, row- and column-vectors
* How to rotate vectors
* And a first introduction into the often very valuable concept of "broadcasting"

author: Thomas Haslwanter, date: Feb-2017

* In order to test the matrix multiplication section you will need Python 3.5.
* As this version is not yet standard I would recommend an environment manager like Anaconda to install an environment where you can use Python 3.5+
* Check your version with python -V

edits by: Perry Radau, April 19, 2017

## Generating Data

### Generating Evenly Spaced Vectors

In [18]:
# import standard packages
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.mlab import frange

# To make the display prettier
%precision 3

'%.3f'

In [19]:
# Note that with "arange" the last value is NOT included!
x = np.arange(1,5,0.5)
x

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [20]:
# "linspace" produces a given number of linearly spaced numbers
y = np.linspace(0,1,11)
y

array([ 0. ,  0.1,  0.2,  0.3,  0.4,  0.5,  0.6,  0.7,  0.8,  0.9,  1. ])

In [21]:
# "frange" includes the last value
z = frange(1,3)
z

array([ 1.,  2.,  3.])

### Generating Matrices

In [22]:
# Unlike MATLAB, Python by default generates vectors, NOT matrices!
zero_vector = np.zeros(3)
zero_vector

array([ 0.,  0.,  0.])

In [23]:
# "np.zeros" and "np.ones" generate zeros and ones, respecitvely.
# They only take ONE input argument, which can be a number or a tuple:
zero_matrix = np.zeros( (3,3))
zero_matrix

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [24]:
# Note: "np.random.randn" in contrast can use more than one input argument:
np.random.randn(3,2)

array([[ 0.416, -0.204],
       [ 0.593,  0.619],
       [ 0.12 ,  0.454]])

In [25]:
# Here an example of how to conveniently generate a matrix of column vectors:

phi = np.deg2rad(np.arange(0,360,30))
sines = np.sin(phi)
cosines = np.cos(phi)

data_mat = np.column_stack((sines, cosines))

print(np.round(data_mat, 2))


[[ 0.    1.  ]
 [ 0.5   0.87]
 [ 0.87  0.5 ]
 [ 1.    0.  ]
 [ 0.87 -0.5 ]
 [ 0.5  -0.87]
 [ 0.   -1.  ]
 [-0.5  -0.87]
 [-0.87 -0.5 ]
 [-1.   -0.  ]
 [-0.87  0.5 ]
 [-0.5   0.87]]


###  Generate Row- and Column-vectors

In [26]:
# A row-vector can be generated like this ...
row_vector = np.array([1,2,3])
row_vector

array([1, 2, 3])

In [27]:
# ... or equivalently like that
row_vector2 = np.r_[3,4,5]
row_vector2

array([3, 4, 5])

In [28]:
# I know the syntax for generating column-vectors are all a bit weird :(
col_vector = np.c_[[4,5,6]]
col_vector

array([[4],
       [5],
       [6]])

In [29]:
# This one uses the command "np.newaxis" to generate a column vector ....
row_vector[..., np.newaxis]

array([[1],
       [2],
       [3]])

In [30]:
# ... and here is how to use the "reshape" command: the "-1" means "however many there are":
np.reshape(row_vector, (-1,1))

array([[1],
       [2],
       [3]])

## Working with Vectors and Matrices

### Rotation of a vector

In [31]:
# Rotation matrix for a rotation by 30 deg
alpha = np.deg2rad(30)
rot_mat = np.array([[np.cos(alpha), -np.sin(alpha)],
                    [np.sin(alpha), np.cos(alpha)]])

# Note that there are two ways to specify a matrix multiplication
# 1) dot is the same as matrix multiplication only for 1-D or 2-D arrays. See docs for N-D.
vec = np.r_[1,0]
vec_rotated = rot_mat.dot(vec)
# 2) matmul is for general N-D matrix multiplication
vec_rotated_2 = np.matmul(rot_mat,vec) #for Python >3.5
vec_rotated_3 = rot_mat @ vec # operator form of matmul

# Show the results
print(rot_mat)
print('I rotated {0} into {1}'.format(str(vec), str(vec_rotated)))
print("matmul is equivalent?", np.all(vec_rotated == vec_rotated_2))
print("@ is equivalent?",np.all(vec_rotated == vec_rotated_3))

[[ 0.866 -0.5  ]
 [ 0.5    0.866]]
I rotated [1 0] into [ 0.866  0.5  ]
matmul is equivalent? True
@ is equivalent? True


In [44]:
#For tensor calculations we can also use matmul
N = np.arange(16).reshape((4,2,2))
M = np.arange(4).reshape(2,2)
print("N")
print(N)
print("M")
print(M)
print("NxM")
print(N @ M)


N
[[[ 0  1]
  [ 2  3]]

 [[ 4  5]
  [ 6  7]]

 [[ 8  9]
  [10 11]]

 [[12 13]
  [14 15]]]
M
[[0 1]
 [2 3]]
NxM=
[[[ 2  3]
  [ 6 11]]

 [[10 19]
  [14 27]]

 [[18 35]
  [22 43]]

 [[26 51]
  [30 59]]]


### "Broadcasting"
In *numpy*, "broadcasting" is a convenient way of adding numbers or vectors to a matrix, is the dimensions match up.

Here, I show how to subtract the mean value from each column:

In [41]:
# Generate some data
data = np.arange(15).reshape((5,3))
data

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [33]:
# overall mean
np.mean(data)

7.000

In [34]:
# each column is averaged, over all rows
np.mean(data, axis=0)

array([ 6.,  7.,  8.])

In [35]:
# Now we use "broadcasting" to subtract the mean of each column:
# if the second index matches, the operation is applied to each row:
data - np.mean(data, axis=0)

print("This requires no. columns of data to equal rows of np.mean(data,axis=0)")
print("In this case it is:")
print(data.shape[1]== np.mean(data,axis=0).shape[0])

This requires no. columns of data to equal rows of np.mean(data,axis=0)
True


In [40]:
# This only works on the last index! The following line will fail
#data - np.mean(data, axis=1)
# each row is averaged, over all columns
print(np.mean(data, axis=1))
print("data - np.mean(data, axis=1)")
print("The above line requires no. columns of data to equal rows of np.mean(data,axis=1)")
print("In this case it is:")
print(data.shape[1]== np.mean(data,axis=1).shape[0])

[  1.   4.   7.  10.  13.]
data - np.mean(data, axis=1)
The above line requires no. columns of data to equal rows of np.mean(data,axis=1)
In this case it is:
False
